package com.martinetherton.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.sql.Date;

/**
 * Created by martin on 23/05/17.
 */
@Entity
@Table(name = "users")
public class User {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @NotNull
    private String firstName;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public long getId() {

        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getSurname() {

        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @NotNull
    private String surname;

    // Public methods

    public User() { }

    public User(long id) {
        this.id = id;
    }

    public User(String firstName, String surname) {
        this.firstName = firstName;
        this.surname = surname;
    }


    private String placeOfBirth;

    public String getPlaceOfBirth() {
        return placeOfBirth;
    }

    public void setPlaceOfBirth(String placeOfBirth) {
        this.placeOfBirth = placeOfBirth;
    }

    private Date dateOfBirth;

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    private String branch;
    public String getBranch() {
        return branch;
    }
    public void setBranch(String branch) {
        this.branch = branch;
    }

    private long fatherId;
    private long motherId;
    private String gender;

    public long getFatherId() {
        return fatherId;
    }
    public long getMotherId() {
        return motherId;
    }
    public String getGender() {
        return gender;
    }

    public void setFatherId(long fatherId) {
        this.fatherId = fatherId;
    }

    public void setMotherId(long motherId) {
        this.motherId = motherId;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    private String longitude;
    private String latitude;

    public String getLongitude() {return longitude;}
    public String getLatitude() {return latitude;}


}
